---
openapi: 3.0.3
info:
  title: Claims
  version: 1.0.0
  contact: {}
servers:
  - url: "perpetualmotioninsurance.com"
paths:
  "/claims":
    get:
      summary: Get all claims
      description: Get all claims open by assigned agent. 
      operationId: getClaims
      parameters:
      - name: agentId
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "Claims retrieved successfully"
  /claims/create:
    post:
      summary: Create a claim
      description: Create a claim by passing in the relevant customer and claim information. Note that an id and status will be assigned in the system and should not be passed in the request at this stage. 
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  example: "AUTO"
                created:
                  type: string
                  example: "09/15/2020"
                lastUpdated:
                  type: string
                  example: "08/01/2021"
                agentId: 
                  type: string
                  example: "0873859"
                customerId: 
                  type: string
                  example: "93005738"
            example:
              created: "09/15/2020"
              type: "AUTO"
              lastUpdated: "08/01/2021"
              agentId: "0873859"
              customerId: "93005738"
      responses:
        "201":
          description: "Claim created successfully"
  /claims/{claimId}/image:
    post:
      summary: Add image to claim
      description: Create a claim by passing in the relevant customer and claim information. Note that an id and status will be assigned in the system and should not be passed in the request at this stage. 
      operationId: addImage
      parameters:
          - name: claimId
            in: path
            required: true
            schema:
                type: string

      requestBody:
        content:
          form-data:
            schema:
              type: object
              properties:
                type:
                  type: string
                  example: "AUTO"
                created:
                  type: string
                  example: "09/15/2020"
                lastUpdated:
                  type: string
                  example: "08/01/2021"
                agentId: 
                  type: string
                  example: "0873859"
                customerId: 
                  type: string
                  example: "93005738"
            example:
              created: "09/15/2020"
              type: "AUTO"
              lastUpdated: "08/01/2021"
              agentId: "0873859"
              customerId: "93005738"
      responses:
        "201":
          description: "Image added successfully"
    get:
      summary: Get all images associtaed with this claim
      description: Get all images associtaed with this claim. 
      operationId: getClaimImages
      parameters:
      - name: claimId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "Claims retrieved successfully"